name: "Gito: AI Code Reviewer"
on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
    inputs:
      pr_number:
        description: "Pull Request number"
        required: true
jobs:
  review:
    runs-on: ubuntu-latest
    permissions: { contents: read, pull-requests: write } # 'write' for leaving the summary comment
    steps:
    - uses: actions/checkout@v4
      with: { fetch-depth: 0 }
    - name: Set up Python
      uses: actions/setup-python@v5
      with: { python-version: "3.13" }
    - name: Install Gito
      run: pip install gito.bot~=2.0
    - name: Run AI code review
      env:
        # OpenAI Setup:
        # LLM_API_KEY: ${{ secrets.LLM_API_KEY }}
        # LLM_API_TYPE: openai
        # MODEL: "gpt-4.1"
        LLM_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        LLM_API_TYPE: anthropic
        MODEL: "claude-sonnet-4-20250514"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        LINEAR_API_KEY: ${{ secrets.LINEAR_API_KEY }}
        GITO_DEBUG: "1"
        PR_NUMBER_FROM_WORKFLOW_DISPATCH: ${{ github.event.inputs.pr_number }}
      run: |
        gito --verbose review
        gito github-comment --token "$GITHUB_TOKEN"
    - uses: actions/upload-artifact@v4
      with:
        name: gito-code-review-results
        path: |
          code-review-report.md
          code-review-report.json